language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.gradle
deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew -Pbintray_user=$bintray_user -Pbintray_api_key=$bintray_api_key bintrayUpload
  on:
    branch: release